# Generated by Django 4.1.7 on 2023-04-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employer_name", models.CharField(max_length=255)),
                ("employer_logo", models.CharField(max_length=1000)),
                ("job_publisher", models.CharField(max_length=255)),
                ("job_id", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("job_employment_type", models.CharField(max_length=255)),
                ("job_apply_link", models.CharField(max_length=255)),
                ("job_description", models.TextField(null=True)),
                ("job_city", models.CharField(max_length=255)),
                ("job_state", models.CharField(max_length=255)),
                ("job_country", models.CharField(max_length=255)),
                ("job_google_link", models.CharField(max_length=1000)),
                ("job_highlights", models.JSONField()),
            ],
        ),
    ]
