# Generated by Django 4.1.7 on 2023-04-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="employer_logo",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_apply_link",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_employment_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_google_link",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_highlights",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_publisher",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_state",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
